[NOT-3026] Notification
ditointernet/sdk_mobile_flutter pull request #11
Opened 2024-06-11 10:53 UTC by anamachadoldo

2024-06-11 12:53 UTC, igorgsduarte requested changes

2024-06-11 12:53 UTC, igorgsduarte commented on README.md
> +  dito.notificationService().showLocalNotification(NotificationEntity(
Aqui deveriamos ter o uso da entity? não deveria ser a nível de domínio? (dentro da Interface ou repository)

2024-06-11 12:53 UTC, igorgsduarte commented on example/lib/app_form.dart
> +    String email = "teste.sdk2@dito.com.br";
vale deixar 222 só por garantia de CPF inválido mesmo

2024-06-11 12:53 UTC, igorgsduarte commented on package/lib/dito_sdk.dart
> +    return await _notificationService.registryMobileToken(token);
o notification não seria um service, mas um notificationInterface. Service é algo que vai ficar rodando na thread ao lado do main process. Neste caso vc só está fazendo interface com as demais clases.

2024-06-11 12:53 UTC, igorgsduarte commented on package/lib/notification/notification_controller.dart
> +// Precisa completar a config no app? https://firebase.flutter.dev/docs/messaging/notifications/#notification-channels
o channels está logo abaixo não?

2024-06-11 12:53 UTC, igorgsduarte commented on package/lib/notification/notification_repository.dart
> +  final DitoApi _ditoApi = DitoApi();
o que acha de chamar apenas de _api? já que tudo é contexto Dito.

2024-06-11 12:53 UTC, igorgsduarte commented on package/lib/notification/notification_repository.dart
> +    }
ios não tem essa configuração, ele deve ser feito diretamente na construção do app

2024-06-11 12:53 UTC, igorgsduarte commented on package/lib/notification/notification_repository.dart
> +        await FirebaseMessaging.instance.getInitialMessage();
aqui vai buscar as mensagem que não foi possível receber, ex: aparelho desligado, ou app travado, etc... A informação de que a mensagem não foi entregue fica salva no firebase, e ao invocar esse método vc resgata todas as mensagem e a envia para o onMessage.

2024-06-11 12:53 UTC, igorgsduarte commented on package/lib/notification/notification_repository.dart
> +            badge: true, sound: true, alert: true);
sim, vale adicionar o IF para ios

2024-06-11 12:53 UTC, igorgsduarte commented on package/lib/notification/notification_service.dart
> +  late NotificationController _controller;
o controller não poderia ser um singleton?
ou pq ele só não vira uma instância nova, assim o late não é necessário.

2024-06-11 12:53 UTC, igorgsduarte commented on package/lib/notification/notification_service.dart
> +class NotificationService {
Aqui seria um interface e não um service

2024-06-11 12:53 UTC, igorgsduarte commented on package/lib/notification/notification_service.dart
> +      StreamController<DataPayload>.broadcast();
os stream são as listas contendo os dados. Elas deve ficar dentro do repository, já que é a camada que cuida dos dados e é única.

2024-06-11 12:53 UTC, igorgsduarte commented on package/lib/notification/notification_service.dart
> +  }
não precisa

2024-06-11 12:53 UTC, igorgsduarte commented on package/lib/notification/notification_service.dart
> +  }
isso iria para dentro do repository

2024-06-11 13:26 UTC, anamachadoldo commented on example/lib/app_form.dart
> +    String email = "teste.sdk2@dito.com.br";
São os dados do usuário de teste que a gente tá usando para testar no dito-feras

2024-06-11 13:28 UTC, anamachadoldo commented on package/lib/notification/notification_controller.dart
> +// Precisa completar a config no app? https://firebase.flutter.dev/docs/messaging/notifications/#notification-channels
Sim, mas de acordo com essa documentação: https://firebase.flutter.dev/docs/messaging/notifications/#notification-channels 

> Once created, we can now update FCM to use our own channel rather than the default FCM one. To do this, open the android/app/src/main/AndroidManifest.xml file for your FlutterProject project. Add the following meta-data schema within the application component:

2024-06-11 13:29 UTC, anamachadoldo commented on package/lib/notification/notification_repository.dart
> +  final DitoApi _ditoApi = DitoApi();
E no arquivo dito_sdk alteramos tbm?

2024-06-11 13:34 UTC, anamachadoldo commented on package/lib/notification/notification_repository.dart
> +        await FirebaseMessaging.instance.getInitialMessage();
Pelo código também tinha entendido dessa forma, mas pela documentação, o que entendi, é que são funções para criar algum comportamento quando o usuário abrir o app ao clicar na mensagem. https://firebase.flutter.dev/docs/messaging/notifications/#handling-interaction

2024-06-11 13:43 UTC, anamachadoldo commented on package/lib/notification/notification_service.dart
> +      StreamController<DataPayload>.broadcast();
Mas, pensando na interface com esse papel de conectar as demais classes, os momentos que adicionamos coisas nessa lista são: `onMessage`( que é chamado no `repository` e na função de `backgroundHandler` no dito_sdk) e no `onSelectNotification` (que é chamado a partir do `controller`). As ações no listen chamam o `controller` e `ditoApi`. 
Deixei na interface para centralizar esse gerenciamento e conexões. E o repository fica responsável somente pela parte que ele realmente altera, que é quando chega a mensagem e ele chama o onMessage. O que acha?

2024-06-11 13:53 UTC, anamachadoldo commented on package/lib/notification/notification_repository.dart
> +    }
De acordo com aqui: https://firebase.google.com/docs/reference/android/com/google/firebase/messaging/FirebaseMessaging#setAutoInitEnabled(boolean) e aqui: https://firebase.google.com/docs/cloud-messaging/flutter/client?hl=pt-br#access_the_registration_token
Parece que pode ser utilizado para os dois

2024-06-11 14:14 UTC, igorgsduarte commented on package/lib/notification/notification_controller.dart
> +// Precisa completar a config no app? https://firebase.flutter.dev/docs/messaging/notifications/#notification-channels
então o que está faltando podemos implementar de uma vez não?

2024-06-11 14:14 UTC, igorgsduarte commented on package/lib/notification/notification_repository.dart
> +  final DitoApi _ditoApi = DitoApi();
creio que sim, fica mais simples a identificação. O que acha?

2024-06-11 14:15 UTC, igorgsduarte commented on package/lib/notification/notification_service.dart
> +      StreamController<DataPayload>.broadcast();
blz, faz sentido.

2024-06-12 12:01 UTC, anamachadoldo commented on package/lib/notification/notification_controller.dart
> +// Precisa completar a config no app? https://firebase.flutter.dev/docs/messaging/notifications/#notification-channels
A outra parte da configuração seria uma alteração no arquivo AndroidManifest do app

2024-06-12 12:11 UTC, anamachadoldo commented on package/lib/notification/notification_service.dart
> +  late NotificationController _controller;
Vou precisar da sua ajuda nessa parte

2024-06-12 12:55 UTC, igorgsduarte requested changes

2024-06-12 12:55 UTC, igorgsduarte commented on package/lib/dito_sdk.dart
> +  Future<String?> getMobileToken() async {
como já estamos em um contexto mobile, faz sentido ser apenas `getToken`?

2024-06-12 12:55 UTC, igorgsduarte commented on package/lib/dito_sdk.dart
>    Future<http.Response> registryMobileToken({required String token}) async {
e se deixar opcional o token e se vazio pegar do firebase?

2024-06-12 12:55 UTC, igorgsduarte commented on package/lib/dito_sdk.dart
>    Future<http.Response> removeMobileToken({required String token}) async {
mesma questão do item acima

2024-06-12 12:55 UTC, igorgsduarte commented on package/lib/notification/notification_repository.dart
> +    }
pois eh, ontem estava lendo a doc nova, pode ser usado nos dois
sendo assim, faz sentido remover o if

2024-06-12 12:55 UTC, igorgsduarte commented on package/lib/notification/notification_repository.dart
> +        await FirebaseMessaging.instance.getInitialMessage();
realmente na doc é diferente o entendimento. Mas faz sentido manter pelo que entendi, pq ele vai disparar o RemoteMessage quando o app estiver fechado e um push receber o click, ai ao abrir o app o remoteMessage dispara.

2024-06-12 12:55 UTC, igorgsduarte commented on package/lib/notification/notification_repository.dart
> +        await FirebaseMessaging.instance.getInitialMessage();
recomendam usar o RemoteMessage e o onMessage para deixar mais simples a UX

2024-06-12 17:50 UTC, merged