[NOT-3027]
ditointernet/sdk_mobile_flutter pull request #13
Opened 2024-06-13 14:32 UTC by anamachadoldo

2024-06-13 15:04 UTC, igorgsduarte requested changes

2024-06-13 15:04 UTC, igorgsduarte commented on package/lib/dito_sdk.dart
> -  }
esse seria bom manter, pois podemos em algum momento ter a possibilidade de remover um token que vem do algum outro local, talvez agluem controle os token e queira manter apenas o mais atual e deletar os outros dispositivos, neste caso temos que dar a possibilidade de enviar um token dinamico

2024-06-13 15:04 UTC, igorgsduarte commented on package/lib/notification/notification_repository.dart
> +  _handleToken() async {
faltou tipar o retorno 
```dart
void _handleToken() async
```

ele sempre é chamado em caso tenha alguma mudança?

2024-06-13 15:04 UTC, igorgsduarte commented on package/lib/notification/notification_repository.dart
> +      final lastToken = _userInterface.data.token;
no caso de abrir o app, o token já registrado, o lastToken não viria vazio? 
se eu tentar remover como vai identificar o lastToken?

2024-06-13 16:58 UTC, anamachadoldo commented on package/lib/notification/notification_repository.dart
> +  _handleToken() async {
o handleToken não, só o listen do tokenRefresh

2024-06-13 16:59 UTC, anamachadoldo commented on package/lib/notification/notification_repository.dart
> +      final lastToken = _userInterface.data.token;
Quando abrir o app ele vai inicializar o `_userInterface.data.token` com o token atual

2024-06-18 12:58 UTC, igorgsduarte commented on package/lib/notification/notification_interface.dart
> +  removeToken(String token) => _repository.removeToken(token);
esses métodos tbem poderiam ficar dentro do dito sdk, o dev pode querer deletar algum outro token que não seja o atual. Sendo assim vale ser opcional o param token, caso `null` pegamos do firebase

2024-06-18 12:58 UTC, igorgsduarte commented on package/lib/notification/notification_interface.dart
> +  removeToken(String token) => _repository.removeToken(token);
e método de adicionar tbem deveria

2024-06-19 17:28 UTC, igorgsduarte approved these changes

2024-06-19 17:33 UTC, merged