[NOT-3216] SDK mostrando notificação duplicada
ditointernet/sdk_mobile_flutter pull request #19
Opened 2024-08-12 13:40 UTC by anamachadoldo

2024-08-12 14:36 UTC, igorgsduarte requested changes

2024-08-12 14:36 UTC, igorgsduarte commented on package/lib/dito_sdk.dart
> +    await _notificationInterface.initialize(true);
aqui não deveria então chamar o initializePushNotificationService()?

2024-08-13 13:34 UTC, anamachadoldo commented on example/lib/main.dart
> +Future<void> _firebaseMessagingBackgroundHandler() async {
Essa função não está sendo chamada mais com a remoção da linha 19. Então, a notificação em background não ta passando pela SDK, não?

2024-08-20 13:52 UTC, igorgsduarte approved these changes

2024-08-20 13:52 UTC, merged